### ISSUE TITLE
Fix "GuestAdditions seems to be installed correctly, but not running" issue

### ISSUE THREAD

**Issue by michael-schnell** [fuinorg/vagrant-packet-builder#9]
### Failure
The virtualbox installation for Lubuntu 18.04 fails with "mount: /vagrant: wrong fs type, bad option, bad superblock on vagrant, missing codepage or helper program, or other error." - The vagrant vbguest plugin shows for `vagrant vbguest --status` the message "GuestAdditions seems to be installed correctly, but not running". 

The same thing works fine for Lubuntu 17.10.1 with [this branch](https://github.com/fuinorg/lubuntu-developer-vm/tree/lubuntu-17.10.1-alternate-amd64).

### Current workaround
There is a discussion [here](https://github.com/dotless-de/vagrant-vbguest/issues/202) that has a suggested a workaround that is now used for this project (See this [commit](https://github.com/fuinorg/vagrant-packet-builder/commit/59e52bdcc99ce9679a6e45c750f8f68996aa97e3)):
```
vagrant up --provider virtualbox 2>&1 | tee ./vagrant.log
vagrant vbguest --do install 2>&1 | tee ./vagrant.log
vagrant reload 2>&1 | tee ./vagrant.log
vagrant halt 2>&1 | tee ./vagrant.log
```
### Expected bahavior
The Vagrant virtualbox build should run without above workaround. The task is to investigate what the root cause is, to fix it and then to remove the workaround.

### Steps to reproduce
1. Checkout [https://github.com/fuinorg/lubuntu-developer-vm](https://github.com/fuinorg/lubuntu-developer-vm) (master)
2. Run `vagrant up --provider virtualbox`

### Additional information
The Vagrant build is based on a [Vagrant base box](https://app.vagrantup.com/fuin/boxes/lubuntu-18.04-alternate-amd64/) that is created by [this project](https://github.com/fuinorg/lubuntu-vagrant-base-box). It's not 100% clear if the problem is actually in the base box or in the [lubuntu-developer-vm](https://github.com/fuinorg/lubuntu-developer-vm) Vagrant project.

**Comment by ashemenev** [comment]
It looks like a bug in the virtualbox version. Update to version 5.2.12 and do not forget to perform `vagrant plugin install vagrant-vbguest` (this is present in the playbook) before `vagrant up --provider virtualbox`

**Comment by michael-schnell** [comment]
Fixed - Was a bug in VirtualBox
